# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            RYE Pages
description:      Exploring
# domain:           ztpala.com
email:            r207ye@gmail.com
twitter_username: fayefayeVLT
github_username:  ryage
github_repo:      https://github.com/ryage/ryage.github.io
# google_analytics: UA-5531632-1
timezone:         America/New_York
# subscribe:        http://feed.ztpala.com
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME
header_pages:
  - apps.md
  - tag.md
  - category.md
  - archive.md
  - search.html
